
name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        pwsh: ['7.4.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: PowerShell/PowerShell-For-GitHub-Actions@v1
        with:
          version: ${{ matrix.pwsh }}
      - name: Install modules
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester,PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Lint
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Recurse -Severity Warning -ReportSummary
      - name: Test
        shell: pwsh
        run: |
          Invoke-Pester -Path ./tests -CI
